name: app
description: Airqo mobile application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# android test
version: 1.21.30+12135
# ios testflight
#version: 1.21.11+12115

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.0.8
  flutter_launcher_icons: ^0.9.2
  google_maps_flutter: ^2.0.3
  json_annotation: ^4.3.0
  http: ^0.13.4
  sqflite: ^2.0.0+4
  cached_network_image: ^3.1.0
  geolocator: ^7.7.1
  flutter_local_notifications: ^8.1.1+2
  url_launcher: ^6.0.12
  path_provider: ^2.0.6
  animations: ^2.0.2
  provider: ^6.0.1
  charts_flutter:
    git:
      url: git://github.com/google/charts.git
      path: charts_flutter
  intl: ^0.17.0
  uuid: ^3.0.4
  flutter_svg: ^0.23.0+1
  camera: ^0.9.4+3
  mime: ^1.0.0
  firebase_messaging: ^10.0.9
  firebase_core: ^1.8.0
  location: ^4.3.0
  cloud_firestore: ^2.5.4
  firebase_auth: ^3.1.3
  change_app_package_name: ^1.0.0
  image_picker: ^0.8.4+2
  country_list_pick: ^1.0.1+5
  shimmer: ^2.0.0
  google_fonts: ^2.1.0
  flutter_inappwebview: ^5.3.2
  in_app_review: ^2.0.3
  sentry_flutter: ^6.0.1
  firebase_analytics: ^8.3.4
  lottie: ^1.2.1
  share_plus: ^3.0.4
  flutter_secure_storage: ^4.2.1
  show_more_text_popup: ^0.3.0
  geocoding: ^2.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_ios: "assets/icon/airqo_logo.png"
  image_path_android: "assets/icon/android_logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.4
  json_serializable: ^6.0.1

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    # images
    - assets/images/world-map.png
    - assets/images/know-your-air.png
    - assets/images/splash-image.png
    - assets/images/tips-image.png
    - assets/images/skate.png
    - assets/images/family.png
    - assets/icon/enable_location_icon.png
    - assets/icon/floating_bg.png
    - assets/icon/coming_soon.png
    - assets/images/child.png
    - assets/images/backyard_trash_burning.png
    - assets/images/trash_burning.png
    - assets/images/old_man.png
    - assets/images/pregnant_woman.png

   # icons
    - assets/icon/airqo_logo.png
    - assets/icon/android_logo.png

    # lottie animations
    - assets/lottie/animated_heart.json

    # svg
    - assets/icon/home_icon.svg
    - assets/icon/toggle_icon.svg
    - assets/icon/share_icon.svg
    - assets/icon/tips_image.svg
    - assets/icon/search.svg
    - assets/icon/profile.svg
    - assets/icon/location.svg
    - assets/icon/airqo_home.svg
    - assets/icon/unit.svg
    - assets/icon/PM2.5.svg
    - assets/icon/PM10.svg
    - assets/icon/info_icon.svg
    - assets/icon/loader.svg
    - assets/icon/chart.svg
    - assets/icon/unit.svg
    - assets/icon/tips_image.svg
    - assets/icon/info_icon.svg
    - assets/icon/home_icon.svg
    - assets/icon/tips_graphics.svg
    - assets/icon/onboarding_fav.svg
    - assets/icon/more_arrow.svg
    - assets/icon/back_button.svg
    - assets/icon/location_icon.svg
    - assets/icon/notification_icon.svg
    - assets/icon/star.svg
    - assets/icon/sparkles.svg
    - assets/icon/heart.svg
    - assets/icon/heart_dislike.svg
    - assets/icon/add_avator.svg
    - assets/icon/globe.svg
    - assets/icon/next_arrow.svg
    - assets/icon/enable_notifications_icon.svg
    - assets/icon/enable_location_icon.svg
    - assets/icon/cog.svg
    - assets/icon/empty_notifications.svg
    - assets/icon/floating_bg.svg
    - assets/icon/close.svg
    - assets/icon/onboarding_profile_icon.svg
    - assets/icon/onboarding_hash_tag.svg
    - assets/icon/kya_stars.svg
    - assets/icon/previous_arrow.svg
    - assets/icon/learn_complete.svg
    - assets/icon/profile_edit.svg
    - assets/icon/has_notifications.svg
    - assets/icon/text_clear_btn.svg

    # Language Translation files
    - assets/i18n/en.json

  fonts:
   - family: Inter
     fonts:
       - asset: assets/fonts/Inter-Bold.ttf
       - asset: assets/fonts/Inter-Black.ttf
       - asset: assets/fonts/Inter-ExtraBold.ttf
       - asset: assets/fonts/Inter-ExtraLight.ttf
       - asset: assets/fonts/Inter-Light.ttf
       - asset: assets/fonts/Inter-Medium.ttf
       - asset: assets/fonts/Inter-Regular.ttf
       - asset: assets/fonts/Inter-Thin.ttf
       - asset: assets/fonts/Inter-SemiBold.ttf

# https://fonts.google.com/specimen/Inter?query=inter

# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.

# For details regarding adding assets from package dependencies, see
# https://flutter.dev/assets-and-images/#from-packages

# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packages
