name: app
description: Airqo mobile application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.21.10+12114


environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.0.0
  webview_flutter: ^2.0.4
  shared_preferences: ^2.0.5
  flutter_launcher_icons: ^0.9.0
  google_maps_flutter: ^2.0.3
  json_annotation: ^4.0.1
  http: ^0.13.1
  sqflite: ^2.0.0+3
  cached_network_image: ^3.0.0
  geolocator: ^7.0.3
  flutter_local_notifications: ^8.1.1+2
  share: ^2.0.1
  url_launcher: ^6.0.3
  path_provider: ^2.0.1
  animations: ^2.0.0
  provider: ^6.0.0
  charts_flutter:
    git:
      url: git://github.com/google/charts.git
      path: charts_flutter
  intl: ^0.17.0
  uuid: ^3.0.4
  flutter_slidable: ^0.6.0
  flutter_svg: ^0.22.0
  animated_text_kit: ^4.2.1
  camera: ^0.9.2+2
  mime: ^1.0.0
  font_awesome_flutter: ^9.0.0
  firebase_messaging: ^10.0.6
  firebase_core: ^1.6.0
  location: ^4.3.0
  geocoder: ^0.2.1
  flutter_html: ^2.1.2
  cloud_firestore: ^2.5.3
  firebase_auth: ^3.1.3
  change_app_package_name: ^1.0.0
  image_picker: ^0.8.4+2
  country_list_pick: ^1.0.1+5
  firebase_storage: ^10.0.5
  shimmer: ^2.0.0
  google_fonts: ^2.1.0
  carousel_slider: ^4.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_ios: "assets/icon/airqo_logo.png"
  image_path_android: "assets/icon/android_logo.png"
dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.4
  pedantic: ^1.11.0
  json_serializable: ^4.1.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    # images
    - assets/images/good-face.png
    - assets/images/moderate-face.png
    - assets/images/unhealthy-face.png
    - assets/images/very-unhealthy-face.png
    - assets/images/sensitive-face.png
    - assets/images/hazardous-face.png
    - assets/images/historical.png
    - assets/images/map.png
    - assets/images/world-map.png
    - assets/images/heart.png
    - assets/images/target.png
    - assets/images/baby.png
    - assets/images/cycling.png
    - assets/images/face-mask.png
    - assets/images/jogging.png
    - assets/images/old.png
    - assets/images/community.png
    - assets/images/pregnant-woman.png
    - assets/images/know-your-air.png
    - assets/images/splash-image.png
    - assets/images/tips-image.png
    - assets/images/skate.png

   # icons
    - assets/icon/airqo_logo.png
    - assets/icon/airqo_logo.jpg
    - assets/icon/airqo_logo_tagline.jpg
    - assets/icon/airqo_logo_tagline_transparent.png
    - assets/icon/airqo_logo.png
    - assets/icon/transparent_logo.png
    - assets/icon/android_logo.png

    # svg
    - assets/icon/home_icon.svg
    - assets/icon/toggle_icon.svg
    - assets/icon/fav_icon.svg
    - assets/icon/share_icon.svg
    - assets/icon/tips_image.svg
    - assets/icon/search.svg
    - assets/icon/profile.svg
    - assets/icon/location.svg
    - assets/icon/airqo_home.svg
    - assets/icon/unit.svg
    - assets/icon/PM2.5.svg
    - assets/icon/info_icon.svg
    - assets/icon/loader.svg
    - assets/icon/chart.svg
    - assets/icon/unit.svg
    - assets/icon/tips_image.svg
    - assets/icon/info_icon.svg
    - assets/icon/home_icon.svg
    - assets/icon/tips_graphics.svg
    - assets/icon/onboarding_fav.svg
    - assets/icon/more_arrow.svg
    - assets/icon/back_button.svg
    - assets/icon/location_icon.svg
    - assets/icon/notification_icon.svg

    # Language Translation files
    - assets/i18n/en.json

  fonts:
   - family: OpenSans
     fonts:
       - asset: assets/fonts/OpenSans-Bold.ttf
       - asset: assets/fonts/OpenSans-BoldItalic.ttf
       - asset: assets/fonts/OpenSans-ExtraBold.ttf
       - asset: assets/fonts/OpenSans-Light.ttf
       - asset: assets/fonts/OpenSans-Regular.ttf
       - asset: assets/fonts/OpenSans-Semibold.ttf

       - asset: assets/fonts/Inter-Bold.ttf
       - asset: assets/fonts/Inter-Black.ttf
       - asset: assets/fonts/Inter-ExtraBold.ttf
       - asset: assets/fonts/Inter-ExtraLight.ttf
       - asset: assets/fonts/Inter-Light.ttf
       - asset: assets/fonts/Inter-Medium.ttf
       - asset: assets/fonts/Inter-Regular.ttf
       - asset: assets/fonts/Inter-Thin.ttf
       - asset: assets/fonts/Inter-SemiBold.ttf

# https://fonts.google.com/specimen/Inter?query=inter

# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.

# For details regarding adding assets from package dependencies, see
# https://flutter.dev/assets-and-images/#from-packages

# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packages
