apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.env.deployment_name }}
  namespace: {{ .Values.appMode }}
  labels: {{ .Values.env.labels }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.env.labels }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.env.labels }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:

      containers:
        - name: {{ .Values.env.labels }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.env.labels }}
              containerPort: {{ .Values.service.targetPort }}
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          env:
            - name: REACT_APP_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.secret }}
                  key: REACT_APP_BASE_URL
            - name: REACT_APP_CLOUDINARY_PRESET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.secret }}
                  key: REACT_APP_CLOUDINARY_PRESET
            - name: REACT_APP_CLOUDINARY_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.secret }}
                  key: REACT_APP_CLOUDINARY_NAME
            - name: REACT_APP_MAPBOX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.secret }}
                  key: REACT_APP_MAPBOX_TOKEN
            - name: REACT_APP_JIRA_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.secret }}
                  key: REACT_APP_JIRA_KEY
            - name: NODE_PATH
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.secret }}
                  key: NODE_PATH
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
