version: '2'

services:              
  web-app:
    container_name: airqo-website
    restart: unless-stopped
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    entrypoint: /app/wsgi-entrypoint.sh    
    volumes:
      - /tmp:/var/lib/postgresql/data
    ports:
      - 8000:8000
    env_file:
      - ../.env
    depends_on:
      - dbHost

  dbHost:
    container_name: airqo-website-db
    restart: unless-stopped
    image: postgres:14.2-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./database/:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    
volumes:
  database:
    driver: local

