###########################################################
# Start deployment of calibrate app - production
###########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airqo-calibrate-app
  namespace: production
spec:
  selector:
    matchLabels:
      app: prod-calibrate-app
  replicas: 2
  template:
    metadata:
      labels:
        app: prod-calibrate-app
    spec:
      containers:
        - name: prod-calibrate-app
          image: us.gcr.io/airqo-250220/airqo-calibrate-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: prod-calibrate
          envFrom:
            - configMapRef:
                name: env-calibrate-prod

---
kind: Service
apiVersion: v1
metadata:
  name: airqo-calibrate-app-svc
  namespace: production
spec:
  selector:
    app: prod-calibrate-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30106
  type: NodePort
