###########################################################
# Start deployment of netmanager frontend - staging
###########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airqo-platform-frontend
  namespace: production
spec:
  selector:
    matchLabels:
      app: airqo-platform
  replicas: 2
  template:
    metadata:
      labels:
        app: airqo-platform
    spec:
      containers:
        - name: airqo-platform
          image: us.gcr.io/airqo-250220/airqo-platform-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: airqo-platform
          env:
            - name: REACT_APP_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: prod-platform-frontend-secret
                  key: REACT_APP_BASE_URL
            - name: REACT_APP_CLOUDINARY_PRESET
              valueFrom:
                secretKeyRef:
                  name: prod-platform-frontend-secret
                  key: REACT_APP_CLOUDINARY_PRESET
            - name: REACT_APP_CLOUDINARY_NAME
              valueFrom:
                secretKeyRef:
                  name: prod-platform-frontend-secret
                  key: REACT_APP_CLOUDINARY_NAME
            - name: REACT_APP_MAPBOX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: prod-platform-frontend-secret
                  key: REACT_APP_MAPBOX_TOKEN
            - name: REACT_APP_JIRA_KEY
              valueFrom:
                secretKeyRef:
                  name: prod-platform-frontend-secret
                  key: REACT_APP_JIRA_KEY
            - name: NODE_PATH
              valueFrom:
                secretKeyRef:
                  name: prod-platform-frontend-secret
                  key: NODE_PATH

---
kind: Service
apiVersion: v1
metadata:
  name: airqo-platform-svc
  namespace: production
spec:
  selector:
    app: airqo-platform
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30101
  type: NodePort
