###########################################################
# Start deployment of platform frontend - staging
###########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airqo-stage-platform-frontend
  namespace: staging
spec:
  selector:
    matchLabels:
      app: sta-platform-ui
  replicas: 2
  template:
    metadata:
      labels:
        app: sta-platform-ui
    spec:
      containers:
        - name: sta-platform-ui
          image: us.gcr.io/airqo-250220/airqo-stage-platform-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: sta-platform-ui
          env:
            - name: REACT_APP_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: stage-platform-frontend-secret
                  key: REACT_APP_BASE_URL
            - name: REACT_APP_CLOUDINARY_PRESET
              valueFrom:
                secretKeyRef:
                  name: stage-platform-frontend-secret
                  key: REACT_APP_CLOUDINARY_PRESET
            - name: REACT_APP_CLOUDINARY_NAME
              valueFrom:
                secretKeyRef:
                  name: stage-platform-frontend-secret
                  key: REACT_APP_CLOUDINARY_NAME
            - name: REACT_APP_MAPBOX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: stage-platform-frontend-secret
                  key: REACT_APP_MAPBOX_TOKEN
            - name: REACT_APP_JIRA_KEY
              valueFrom:
                secretKeyRef:
                  name: stage-platform-frontend-secret
                  key: REACT_APP_JIRA_KEY
            - name: NODE_PATH
              valueFrom:
                secretKeyRef:
                  name: stage-platform-frontend-secret
                  key: NODE_PATH

---
kind: Service
apiVersion: v1
metadata:
  name: airqo-stage-platform-ui-svc
  namespace: staging
spec:
  selector:
    app: sta-platform-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31104
  type: NodePort
