runtime: php55
env: standard
api_version: 1
threadsafe: true

handlers:
  - url: /(.+\.(js|css|gif|png|jpeg|jpg|svg|ico|bmp|ttf|woff|eot|mp4|mp3|pdf))$
    static_files: \1
    upload: .+\.(js|css|gif|png|jpeg|jpg|svg|ico|bmp|ttf|woff|eot|mp4|mp3|pdf)$
    application_readable: true

  - url: /apis/(.+)\.php
    script: apis/\1.php

  - url: /dsa/
    static_files: dsa/index.html
    upload: dsa/index.html

  - url: /docs/
    static_files: docs/Privacy-Policy-For-AirQo.pdf
    upload: docs/Privacy-Policy-For-AirQo.pdf

  - url: /.*
    script: index.php
    secure: always
    redirect_http_response_code: 301
